/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scguo_nativeaudioprocess_MainActivity */

#ifndef _Included_com_scguo_nativeaudioprocess_MainActivity
#define _Included_com_scguo_nativeaudioprocess_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scguo_nativeaudioprocess_MainActivity_MODE_PRIVATE
#define com_scguo_nativeaudioprocess_MainActivity_MODE_PRIVATE 0L
#undef com_scguo_nativeaudioprocess_MainActivity_MODE_WORLD_READABLE
#define com_scguo_nativeaudioprocess_MainActivity_MODE_WORLD_READABLE 1L
#undef com_scguo_nativeaudioprocess_MainActivity_MODE_WORLD_WRITEABLE
#define com_scguo_nativeaudioprocess_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef com_scguo_nativeaudioprocess_MainActivity_MODE_APPEND
#define com_scguo_nativeaudioprocess_MainActivity_MODE_APPEND 32768L
#undef com_scguo_nativeaudioprocess_MainActivity_MODE_MULTI_PROCESS
#define com_scguo_nativeaudioprocess_MainActivity_MODE_MULTI_PROCESS 4L
#undef com_scguo_nativeaudioprocess_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_scguo_nativeaudioprocess_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_scguo_nativeaudioprocess_MainActivity_BIND_AUTO_CREATE
#define com_scguo_nativeaudioprocess_MainActivity_BIND_AUTO_CREATE 1L
#undef com_scguo_nativeaudioprocess_MainActivity_BIND_DEBUG_UNBIND
#define com_scguo_nativeaudioprocess_MainActivity_BIND_DEBUG_UNBIND 2L
#undef com_scguo_nativeaudioprocess_MainActivity_BIND_NOT_FOREGROUND
#define com_scguo_nativeaudioprocess_MainActivity_BIND_NOT_FOREGROUND 4L
#undef com_scguo_nativeaudioprocess_MainActivity_BIND_ABOVE_CLIENT
#define com_scguo_nativeaudioprocess_MainActivity_BIND_ABOVE_CLIENT 8L
#undef com_scguo_nativeaudioprocess_MainActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_scguo_nativeaudioprocess_MainActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_scguo_nativeaudioprocess_MainActivity_BIND_WAIVE_PRIORITY
#define com_scguo_nativeaudioprocess_MainActivity_BIND_WAIVE_PRIORITY 32L
#undef com_scguo_nativeaudioprocess_MainActivity_BIND_IMPORTANT
#define com_scguo_nativeaudioprocess_MainActivity_BIND_IMPORTANT 64L
#undef com_scguo_nativeaudioprocess_MainActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_scguo_nativeaudioprocess_MainActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_scguo_nativeaudioprocess_MainActivity_CONTEXT_INCLUDE_CODE
#define com_scguo_nativeaudioprocess_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_scguo_nativeaudioprocess_MainActivity_CONTEXT_IGNORE_SECURITY
#define com_scguo_nativeaudioprocess_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_scguo_nativeaudioprocess_MainActivity_CONTEXT_RESTRICTED
#define com_scguo_nativeaudioprocess_MainActivity_CONTEXT_RESTRICTED 4L
#undef com_scguo_nativeaudioprocess_MainActivity_RESULT_CANCELED
#define com_scguo_nativeaudioprocess_MainActivity_RESULT_CANCELED 0L
#undef com_scguo_nativeaudioprocess_MainActivity_RESULT_OK
#define com_scguo_nativeaudioprocess_MainActivity_RESULT_OK -1L
#undef com_scguo_nativeaudioprocess_MainActivity_RESULT_FIRST_USER
#define com_scguo_nativeaudioprocess_MainActivity_RESULT_FIRST_USER 1L
#undef com_scguo_nativeaudioprocess_MainActivity_DEFAULT_KEYS_DISABLE
#define com_scguo_nativeaudioprocess_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_scguo_nativeaudioprocess_MainActivity_DEFAULT_KEYS_DIALER
#define com_scguo_nativeaudioprocess_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef com_scguo_nativeaudioprocess_MainActivity_DEFAULT_KEYS_SHORTCUT
#define com_scguo_nativeaudioprocess_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_scguo_nativeaudioprocess_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_scguo_nativeaudioprocess_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_scguo_nativeaudioprocess_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_scguo_nativeaudioprocess_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    createBufferQueueAudioPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_createBufferQueueAudioPlayer
  (JNIEnv *, jclass);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    createAssetAudioPlayer
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_createAssetAudioPlayer
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    setPlayingAssetAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_setPlayingAssetAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    createUriAudioPlayer
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_createUriAudioPlayer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    setPlayingUriAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_setPlayingUriAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    setLoopingUriAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_setLoopingUriAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    setChannelMuteUriAudioPlayer
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_setChannelMuteUriAudioPlayer
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    setChannelSoloUriAudioPlayer
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_setChannelSoloUriAudioPlayer
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    getNumChannelsUriAudioPlayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_getNumChannelsUriAudioPlayer
  (JNIEnv *, jclass);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    setVolumeUriAudioPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_setVolumeUriAudioPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    setMuteUriAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_setMuteUriAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    enableStereoPositionUriAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_enableStereoPositionUriAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    setStereoPositionUriAudioPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_setStereoPositionUriAudioPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    selectClip
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_selectClip
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    enableRevert
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_enableRevert
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    createAudioRecorder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_createAudioRecorder
  (JNIEnv *, jclass);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    startRecording
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_startRecording
  (JNIEnv *, jclass);

/*
 * Class:     com_scguo_nativeaudioprocess_MainActivity
 * Method:    shutDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scguo_nativeaudioprocess_MainActivity_shutDown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
