/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scguo_twolibslab_MainActivity */

#ifndef _Included_com_scguo_twolibslab_MainActivity
#define _Included_com_scguo_twolibslab_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scguo_twolibslab_MainActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_scguo_twolibslab_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
